name = "MixedModelsExtras"
uuid = "781a26e1-49f4-409a-8f4c-c3159d78c17e"
authors = ["Phillip Alday <me@phillipalday.com> and contributors"]
version = "0.1.2"

[deps]
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
MixedModels = "3, 4"
StatsBase = "0.33"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
